### ISSUE TITLE
You can use 'type' to do this

### ISSUE THREAD

**Issue by umago** [dorkitude/dstruct#1]
obj = type("MyObject", (object, ), {"b1":"v1", "b2":"v2"})
obj.b1 #outputs 'v1'

**Comment by dorkitude** [comment]
That's just class generation.  I'm guessing you didn't read the whole README ;)

DStruct isn't merely about not using dictionaries (there's nothing wrong with dictionaries); it's about using instances of classes that can be declaratively restricted in schema.
